services:
  app:
    image: ghcr.io/aleksioprime/demo-app:latest
    container_name: demo-app
    restart: always
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.demo.rule=PathPrefix(`/demo`)"
      - "traefik.http.routers.demo.entrypoints=web"
      - "traefik.http.middlewares.demo-strip.stripprefix.prefixes=/demo"
      - "traefik.http.routers.demo.middlewares=demo-strip"
      - "traefik.http.services.demo.loadbalancer.server.port=8000"

networks:
  traefik-net:
    external: true