services:
  app:
    image: ghcr.io/aleksioprime/demo-app:20251128-172315
    container_name: demo-app
    restart: always

    labels:
      # Обязательно включить Traefik
      - "traefik.enable=true"

      # --- HTTPS ROUTER ---
      # Уникальный домен для приложения
      - "traefik.http.routers.demo.rule=Host(`demo.aledemo.ru`)"
      - "traefik.http.routers.demo.entrypoints=websecure"
      - "traefik.http.routers.demo.tls.certresolver=myresolver"

      # --- HTTP ROUTER (for redirect) ---
      - "traefik.http.routers.demo-http.rule=Host(`demo.aledemo.ru`)"
      - "traefik.http.routers.demo-http.entrypoints=web"
      - "traefik.http.routers.demo-http.middlewares=redirect-to-https"

      # --- Redirect middleware ---
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # --- INTERNAL PORT ---
      - "traefik.http.services.demo.loadbalancer.server.port=8000"

    networks:
      - traefik-net


networks:
  traefik-net:
    external: true
